name: "go-generator"
version:  "1.0.1"
author: "xxcheng"
port: 19999
mode: "debug"
log:
  filename: "log.log"
  max_size: 30
  max_age:  7
  max_backups:  5
  level:  "info"
mysql:
  host: "localhost"
  port: 3306
  user: "root"
  pass: "pass"
  dbName: "dbName"
redis:
  host: "localhost"
  port: 6379